### ISSUE TITLE
Documentation correction required for schedule_interval

### ISSUE THREAD

**Issue by rajc242** [anandj123/composer-templates#2]
Airflow is supporting schedule_interval with cron expression and preset cron annotation. Please refer [Airflow Doc](https://airflow.apache.org/docs/apache-airflow/1.10.1/scheduler.html)

We required to put value of schedule_interval in single or double quote in config.yaml to avoid error while generating dag.
schedule_interval can be either **'@hourly'** or 0 * * * *. This will not generate error for @.

**Comment by anandj123** [comment]
I fixed the documentation and code so that None as well as @hourly etc. will work. Can you check and confirm?
